# Generated by Django 2.0.2 on 2021-10-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Страница', max_length=64, verbose_name='Название страницы')),
                ('content', models.TextField(blank=True, verbose_name='Содержание страницы')),
            ],
            options={
                'verbose_name_plural': 'Страница',
            },
        ),
    ]
