# Generated by Django 2.0.2 on 2021-10-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='master',
            field=models.CharField(blank=True, default='Мастер-страница', max_length=64, verbose_name='Название мастер-страницы'),
        ),
    ]
