# Generated by Django 3.2.3 on 2021-10-21 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='master',
        ),
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='date_change',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='page',
            name='subpage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
