# Generated by Django 3.2.3 on 2021-10-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20211021_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='subpage',
            new_name='master_page',
        ),
    ]
