# Generated by Django 3.2.3 on 2021-10-30 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('title', models.CharField(blank=True, default='Название программы', max_length=64, verbose_name='Название программы')),
                ('date_publicate', models.DateField(default=datetime.date.today)),
                ('date_create', models.DateField(default=datetime.date.today)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Программа',
            },
        ),
    ]
