# Generated by Django 3.2.3 on 2021-11-05 20:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('title', models.CharField(blank=True, default='Ошибка', max_length=64, verbose_name='Название ошибки')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('date_create', models.DateField(default=datetime.date.today)),
                ('date_resolve', models.DateField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, null=True, related_name='_bug_tracker_bug_comments_+', to='comment.Comment')),
            ],
            options={
                'verbose_name_plural': 'Ошибка',
            },
        ),
    ]
