# Generated by Django 3.2.3 on 2021-11-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0002_auto_20211107_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='date_resolve',
            field=models.DateField(blank=True, null=True),
        ),
    ]
