# Generated by Django 3.2.3 on 2021-11-11 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0003_alter_bug_date_resolve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='bug',
            name='date_resolve',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
